spring:
  main.banner-mode: off
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/app_db
    username: root
    password: root
  cache:
    cache-names: additionalData
    caffeine.spec: expireAfterWrite=5m
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db-migration/changelog-master.yml